In [1]:
import numpy as np

In [10]:
a = np.array(["1", "2", "3"])
print(a)

['1' '2' '3']


In [11]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
c = np.array([[(1,2,3),(4,5,6)], [(7,8,9),(10,11,12)]], dtype=int)
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
#ndim
print("a = {}".format(a.ndim))
print("b = {}".format(b.ndim))
print("c = {}".format(c.ndim))

a = 1
b = 2
c = 3


In [14]:
#Shape
print("a = {}".format(a.shape))
print("b = {}".format(b.shape))
print("c = {}".format(c.shape))

a = (3,)
b = (2, 3)
c = (2, 2, 3)


In [15]:
#Item Size
print("a = {}".format(a.itemsize))
print("b = {}".format(b.itemsize))
print("c = {}".format(c.itemsize))

a = 4
b = 4
c = 4


In [16]:
#dtype
print("a = {}".format(a.dtype))
print("b = {}".format(b.dtype))
print("c = {}".format(c.dtype))

a = <U1
b = int32
c = int32


In [17]:
#Size
print("a = {}".format(a.size))
print("b = {}".format(b.size))
print("c = {}".format(c.size))

a = 3
b = 6
c = 12


In [21]:
# Convert an array to different type
integerArr = a.astype(int)
print("{} Converted to {}".format(a, integerArr))
print("After converting, now array is {}".format(integerArr.dtype))

['1' '2' '3'] Converted to [1 2 3]
After converting, now array is int32


In [26]:
# Reshape
print("b = {}".format(a.shape))
print(b)
print("\nAfter reshapng:")
reshaped = b.reshape(3,2)
print("reshaped = {}".format(reshaped.shape))
print(reshaped)

b = (3,)
[[1 2 3]
 [4 5 6]]

After reshapng:
reshaped = (3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [35]:
# Repeat
print(b)
print("\nRow - Repeat")
print(b.repeat(2,0))

print("\nColumn - Repeat")
print(b.repeat(2,1))

[[1 2 3]
 [4 5 6]]

Row - Repeat
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]

Column - Repeat
[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]


In [37]:
#ravel()
print("Flatted array {}".format(b.ravel()))


Flatted array [1 2 3 4 5 6]


In [44]:
alist = [(1,2), (3,4)]
blist = [(1,2), (3,4)]

print("List Sum = {}".format(alist+blist))

aNumpy = np.array([(1,2), (3,4)])
bNumpy = np.array([(1,2)])

print("Numpy Sum: \n {}".format(aNumpy+bNumpy))

aNumpy = [(1,2), (3,4)]
bNumpy = [(1,2), (3,4)]

print("Numpy Sum: \n {}".format(np.add(aNumpy, bNumpy)))


List Sum = [(1, 2), (3, 4), (1, 2), (3, 4)]
Numpy Sum: 
 [[2 4]
 [4 6]]
Numpy Sum: 
 [[2 4]
 [6 8]]


In [47]:
# Arange
print("Numpy Sum: \n {}".format(np.arange(2,25,5)))

Numpy Sum: 
 [ 2  7 12 17 22]
